# Railway currently only supports single service per repo
# For multi-service, deploy frontend separately or use monorepo approach

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on-failure"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
startCommand = "./start.sh"