[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "never"

[[services]]
name = "api"
source = "."
dockerfile = "Dockerfile"

[services.healthcheck]
path = "/health"
timeout = 300
interval = 300

[[services]]
name = "frontend"  
source = "frontend"
dockerfile = "frontend/Dockerfile"

[services.healthcheck]
path = "/"
timeout = 300
interval = 300