# Railway currently only supports single service per repo
# For multi-service, deploy frontend separately or use monorepo approach

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "never"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"